### ISSUE TITLE
STOP: Stopping resource server... STOP: Resource server stopped.

### ISSUE THREAD

**Issue by Adiru3** [MexUK/Essentials#1]
Loading modules...
0/0 Modules loaded, 0 failed
Scanning resources...
Loading resources...
5 resources in the resource cache
Server is starting...
Server is now listening on port 22000 max players 100...
Starting resources...
START: Starting resource server...
STOP: Stopping resource server...
STOP: Resource server stopped.

**Comment by MexUK** [comment]
This is an error with the GTAC server, and no error message was displayed is an error too, thanks for reporting the error I have forwarded this onto the team. Please re-test when the next server version is released, as of this message the current server version is 1.3.4, because it may have been fixed by a commit me and Jack worked on a few days ago for the GTAC server. I'm closing this issue because it appears to be a GTAC error, and not a resource error.
